import React from 'react';
import { usePageStyles } from '../utils/hooks.js';
import { LandingNavbar } from '../components/common.jsx';

export default function Legal({type='about'}){
  usePageStyles(['/css/global.css','/css/navbar.css','/css/landing.css','/css/animation.css','/css/legal.css']);
  if(type==='about'){
    return <><LandingNavbar/><section className="min-h-screen flex items-center justify-center text-center px-10"><div className="max-w-5xl"><p className="text-sky-500 uppercase tracking-[0.3em] mb-8">ABOUT LIFEHUB</p><h1 className="text-7xl font-bold leading-tight">Productivity<br/>should feel<br/>meaningful.</h1></div></section><section className="min-h-screen flex items-center justify-center text-center px-10 bg-slate-50"><div className="max-w-4xl"><p className="text-3xl leading-relaxed text-slate-700">In a world filled with distractions, endless notifications, and increasingly demanding schedules, staying organized has become more difficult than ever before.</p></div></section><section className="min-h-screen flex items-center justify-center text-center px-10"><div className="max-w-4xl"><p className="text-3xl leading-relaxed text-slate-700">Many people rely on multiple applications to manage their daily lives — calendars, task managers, note-taking apps, habit trackers, and focus timers.<br/><br/>Instead of simplifying life, these tools often create fragmented experiences that are difficult to maintain consistently.</p></div></section><section className="min-h-screen flex items-center justify-center text-center px-10 bg-slate-50"><div className="max-w-4xl"><p className="text-3xl leading-relaxed text-slate-700">LIFEHUB was created with a different vision.<br/><br/>A vision where productivity, personal growth, mindfulness, and environmental awareness can coexist within a single ecosystem.</p></div></section><section className="min-h-screen flex items-center justify-center text-center px-10"><div><h1 className="text-7xl font-bold leading-tight">Track Your Life.<br/>Heal Your Earth.</h1></div></section></>;
  }
  const isPrivacy=type==='privacy';
  return <><LandingNavbar/><div className="legal-container"><h1 className="legal-title">{isPrivacy?'Privacy':'Terms'}</h1><div className="legal-divider"></div><p className="legal-updated">Last updated: June 2, 2026</p><div className="legal-content">{isPrivacy ? <><p>This Privacy Policy describes how LIFEHUB handles information, user progress, and productivity data while using the platform.</p><p>LIFEHUB was designed with privacy as a core principle. Most user information remains stored locally within the user's browser and is used solely to improve the user experience.</p><h2>Data Collection</h2><p>LIFEHUB does not require users to submit personal information in order to access core productivity features.</p><p>Tasks, habits, achievements, and productivity statistics are primarily managed within the user's local environment.</p><h2>Local Storage</h2><p>To maintain progress between sessions, LIFEHUB may store information using browser local storage.</p><p>This data remains on the user's device and is not transmitted to external servers.</p><h2>User Rights</h2><p>Users maintain full control over their locally stored data.</p><p>Information can be removed at any time by clearing browser storage.</p></> : <><p>These Terms and Conditions govern the use of LIFEHUB and all related productivity features provided by the platform.</p><h2>Acceptance of Terms</h2><p>By accessing and using LIFEHUB, users agree to comply with these terms.</p><h2>Responsible Use</h2><p>LIFEHUB is intended to support productivity, habit development, focus management, and sustainable lifestyle practices.</p><p>Users are responsible for the accuracy of any information entered into the platform.</p><h2>Platform Availability</h2><p>While every effort is made to ensure reliability, LIFEHUB does not guarantee uninterrupted availability or specific productivity outcomes.</p><h2>Changes to Terms</h2><p>These terms may be updated periodically to reflect improvements and platform changes.</p></>}</div></div></>;
}
