import React,{useEffect,useState} from 'react';
import { usePageStyles, navigate } from '../utils/hooks.js';
import { Link } from '../components/common.jsx';
import { saveRecommended } from '../utils/core.js';

const slides=[
{label:'Quest Rhythm',headline:'A calmer way to know what matters first.',description:'LIFEHUB helps you turn a messy day into a sequence of meaningful actions.',quote:'You do not need to do everything. You only need to know the next right mission.',miniLabel:'Suggested Flow',miniText:'Start with 3 daily quests',symbols:['✓','📌','✨']},
{label:'Habit Energy',headline:'Small routines can become your strongest system.',description:'Consistency feels easier when your habits are visible, trackable, and rewarding.',quote:'The goal is not to become perfect overnight. The goal is to return tomorrow.',miniLabel:'Daily Rhythm',miniText:'Build one habit at a time',symbols:['💧','🔁','🌱']},
{label:'Focus Mode',headline:'Your attention deserves a protected space.',description:'Focus sessions help you slow down, choose one thing, and actually finish it.',quote:'Deep work begins when you stop negotiating with distraction.',miniLabel:'Focus Suggestion',miniText:'Try one 25-minute session',symbols:['⏱','⚡','🌙']},
{label:'Growth Progress',headline:'Progress feels better when you can see it.',description:'XP, levels, streaks, and badges make your daily effort easier to recognize.',quote:'Your growth is not invisible. LIFEHUB turns effort into something you can see.',miniLabel:'Progress Path',miniText:'Earn XP from action',symbols:['🏆','⭐','🔥']},
{label:'Eco Lifestyle',headline:'A better day can also be better for the earth.',description:'Eco side quests help you add simple sustainable choices into your routine.',quote:'Small green actions are still progress when they become part of your lifestyle.',miniLabel:'Green Mission',miniText:'Start with one eco quest',symbols:['🍃','🌍','♻️']}
];
const questions=[
{title:'What do you want to improve first?',description:'Choose the area that feels most important for your current life rhythm.',answers:[['Manage my tasks','I want my daily work to feel clearer and more structured.','quest'],['Build better habits','I want small routines that I can actually maintain.','habit'],['Improve my focus','I get distracted easily and need better deep work sessions.','focus'],['Balance everything','I want a system for tasks, habits, focus, and progress.','balanced']]},
{title:'How does your day usually feel?',description:'This helps LIFEHUB understand the kind of program that fits your lifestyle.',answers:[['Messy and overloaded','Too many things happen at once.','quest'],['Inconsistent','I start routines, but often stop after a few days.','habit'],['Distracted','I struggle to stay locked in.','focus'],['Busy but manageable','I just need a cleaner system.','balanced']]},
{title:'What kind of support do you prefer?',description:'Pick the system that would motivate you the most.',answers:[['Daily quests','Give me missions I can complete one by one.','quest'],['Routine tracker','Help me repeat good habits consistently.','habit'],['Focus timer','Help me enter deep work mode.','focus'],['Progress and rewards','I like XP, levels, and achievement feedback.','balanced']]},
{title:'Do you want eco missions included?',description:'LIFEHUB can add small green side quests to your daily progress.',answers:[['Yes, include eco quests','I want small sustainable actions in my routine.','eco'],['Only simple ones','Give me eco missions that are easy to do.','eco'],['Maybe later','I want to focus on productivity first.','balanced'],['Not for now','Keep my program focused on personal productivity.','focus']]}
];
const programs={quest:{name:'Quest Productivity Program',description:'Your recommended starting point is a structured quest system. LIFEHUB will help you organize tasks, set priorities, and complete your day one mission at a time.',pills:['Daily Quest','Priority','Deadline','Progress']},habit:{name:'Habit Starter Program',description:'Your recommended starting point is habit building. LIFEHUB will help you create simple routines, track consistency, and turn small actions into long-term progress.',pills:['Daily Habit','Streak','Routine','Consistency']},focus:{name:'Focus Builder Program',description:'Your recommended starting point is deep work. LIFEHUB will help you protect your attention, reduce distractions, and build better focus sessions.',pills:['Pomodoro','Deep Work','XP Reward','Discipline']},balanced:{name:'Balanced Life Program',description:'Your recommended starting point is a balanced system. LIFEHUB will combine quests, habits, focus, and progress tracking to help you manage your day with more clarity.',pills:['Quest','Habit','Focus','Achievement']},eco:{name:'Eco Lifestyle Program',description:'Your recommended starting point includes eco side quests. LIFEHUB will help you build a better daily rhythm while adding small sustainable actions to your lifestyle.',pills:['Eco Quest','Green Habit','Side Mission','Eco Points']}};

function Character(){return <div className="character-scene"><span className="floating-symbol one">✨</span><span className="floating-symbol two">🌱</span><span className="floating-symbol three">✓</span><div className="character"><div className="char-hair"></div><div className="char-head"></div><div className="char-body"></div><div className="char-arm left"></div><div className="char-arm right"></div><div className="char-leg left"></div><div className="char-leg right"></div></div></div>}

export default function Onboarding(){
 usePageStyles(['/css/onboarding.css','/css/gamification.css']);
 const [slide,setSlide]=useState(0); const [step,setStep]=useState(0); const [scores,setScores]=useState({quest:0,habit:0,focus:0,balanced:0,eco:0}); const [result,setResult]=useState(null);
 useEffect(()=>{const id=setInterval(()=>setSlide(s=>(s+1)%slides.length),4800); return()=>clearInterval(id)},[]);
 const choose=(value)=>{const next={...scores,[value]:scores[value]+1}; if(step+1>=questions.length){ const key=Object.keys(next).sort((a,b)=>next[b]-next[a])[0]||'balanced'; setResult(programs[key]); saveRecommended({key,...programs[key]}); }else{setScores(next); setStep(step+1);}};
 const q=questions[step]; const active=slides[slide];
 return <><header className="onboard-nav"><Link to="/" className="onboard-brand">LIFEHUB</Link><nav className="onboard-links"><Link to="/">Home</Link><a href="#things">Explore</a><a href="#personalize" className="nav-primary">Personalize</a></nav></header><main>
  <section className="things-section" id="things"><div className="section-shell"><div className="showcase-header"><p className="eyebrow">Things You Can Do with LIFEHUB</p><h1>{active.headline}</h1><p>{active.description}</p></div><div className="quote-carousel-shell"><button className="feature-arrow left" onClick={()=>setSlide((slide-1+slides.length)%slides.length)}>←</button><div className="quote-carousel-window"><div className="quote-carousel">{slides.map((s,i)=>{const prev=(slide-1+slides.length)%slides.length,next=(slide+1)%slides.length;return <article key={s.label} className={`quote-card ${i===slide?'active':i===prev?'prev':i===next?'next':'hidden'}`}><div className="quote-top"><span className="quote-label">{s.label}</span><h2>{s.quote}</h2><p>{s.description}</p></div><div className="quote-bottom"><div className="quote-mini"><span>{s.miniLabel}</span><strong>{s.miniText}</strong></div><Character/></div></article>})}</div></div><button className="feature-arrow right" onClick={()=>setSlide((slide+1)%slides.length)}>→</button></div><div className="feature-dots">{slides.map((_,i)=><button key={i} className={`feature-dot ${i===slide?'active':''}`} onClick={()=>setSlide(i)}></button>)}</div><div className="continue-row"><a href="#personalize" className="primary-btn">Continue to Personalization</a></div></div></section>
  <section className="personalize-section" id="personalize"><div className="section-shell"><div className="personalize-layout"><div className="personalize-intro"><p className="eyebrow">Pre-login Personalization</p><h2>Let LIFEHUB understand your rhythm first.</h2><p>Answer a few short questions so LIFEHUB can recommend a starting program that fits the way you manage tasks, habits, focus, and daily growth.</p><div className="mini-program-preview"><div><span>01</span><p>Choose your focus area</p></div><div><span>02</span><p>Tell us your daily pattern</p></div><div><span>03</span><p>Get your recommended program</p></div></div></div>{!result?<div className="question-card"><div className="question-progress"><div className="progress-bar"><div className="progress-fill" style={{width:`${(step/questions.length)*100}%`}}></div></div><span>{step+1}/{questions.length}</span></div><p className="eyebrow">Question</p><h2>{q.title}</h2><p>{q.description}</p><div className="answer-grid">{q.answers.map(a=><button className="answer-btn" key={a[0]} onClick={()=>choose(a[2])}><h4>{a[0]}</h4><p>{a[1]}</p></button>)}</div></div>:<div className="result-card show lifehub-result-light"><p className="eyebrow">Recommended Program</p><h2>{result.name}</h2><p>{result.description}</p><div className="program-pills">{result.pills.map(p=><span key={p}>{p}</span>)}</div><div className="result-actions"><button className="primary-btn" onClick={()=>navigate('/dashboard')}>Enter Dashboard</button><button className="secondary-btn" onClick={()=>{setResult(null);setStep(0);setScores({quest:0,habit:0,focus:0,balanced:0,eco:0});}}>Retake Questions</button></div></div>}</div></div></section>
 </main></>;
}
